### ISSUE TITLE
处理2.2g的文件，显示out of memory

### ISSUE THREAD

**Issue by wwtBlog** [sing1ee/dict_build#12]

**Comment by wwtBlog** [comment]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Character.valueOf(Character.java:4573)
	at com.googlecode.concurrenttrees.radix.node.concrete.chararray.CharArrayNodeDefault.getIncomingEdgeFirstCharacter(CharArrayNodeDefault.java:84)
	at com.googlecode.concurrenttrees.radix.node.util.NodeCharacterComparator.compare(NodeCharacterComparator.java:30)
	at com.googlecode.concurrenttrees.radix.node.util.NodeCharacterComparator.compare(NodeCharacterComparator.java:26)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.googlecode.concurrenttrees.radix.node.concrete.chararray.CharArrayNodeDefault.<init>(CharArrayNodeDefault.java:71)
	at com.googlecode.concurrenttrees.radix.node.concrete.DefaultCharArrayNodeFactory.createNode(DefaultCharArrayNodeFactory.java:80)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.putInternal(ConcurrentRadixTree.java:511)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.put(ConcurrentRadixTree.java:83)
	at dict.build.FastBuilder.extractWords(FastBuilder.java:438)
	at dict.build.Main.main(Main.java:40)

**Comment by sing1ee** [comment]
这里需要修改一下JVM的默认参数

**Comment by wwtBlog** [comment]
怎么修改呢？能不能详细说一下

**Comment by sing1ee** [comment]
你如果是linux，或者mac，可以执行如下命令
```shell
export JAVA_OPTS=-Xmx2G
./bin/dict_build
```
2G可以根据实际情况替换

**Comment by wwtBlog** [comment]
2g换成文件的大小是吗？

**Comment by sing1ee** [comment]
@wwtBlog 不一定等同文件的大小，你可以不断试验一下。

**Comment by wwtBlog** [comment]
改成了3g，仍然会报错

**Comment by sing1ee** [comment]
我找语料试一下。
