### ISSUE TITLE
java版本有要求吗

### ISSUE THREAD

**Issue by wwtBlog** [sing1ee/dict_build#13]
我在linux开发机上遇到了版本不支持的错误
Exception in thread "main" java.lang.UnsupportedClassVersionError: dict/build/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
我java版本是java version "1.7.0_79"

**Comment by sing1ee** [comment]
直接从源码打包吧，因为我用的jdk1.8以上了。

2017-05-27 13:07 GMT+08:00 wwtBlog <notifications@github.com>:

**Comment by wwtBlog** [comment]
打包以后如何使用呢？现在我是使用dic那个命令来运行的

**Comment by sing1ee** [comment]
1. 安装gradle，在项目目录执行：
```shell
gradle distTar
```
2. 目录下：build/distributions，有一个文件：dict_build-0.0.3.tar，解压
```shell
tar xvf dict_build-0.0.3.tar
```

3. 进入dict_build-0.0.3目录，执行：
```shell
./bin/dict_build your_input_data_file
```

**Comment by wwtBlog** [comment]
打包是打包成jar包吗？只有一个jar包啊，没有build啊

**Comment by sing1ee** [comment]
不是jar包，按照我的步骤，会在build目录下

2017-06-02 10:13 GMT+08:00 wwtBlog <notifications@github.com>:
